config:
  key: 01-dev

#Application Name
spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    #telling the server to register himself in the service registry of the other servers
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    registerWithEureka: false
    fetchRegistry: false
    #serviceUrl:
      #defaultZone: http://ESLGVH4N32.ste.dom:8762/eureka
    healthcheck:
      enabled: true
  instance:
      preferIpAddress: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 30 
      leaseExpirationDurationInSeconds: 5  
  server:
    peer-node-read-timeout-ms: 10000
    enableSelfPreservation: true
    responseCacheUpdateInvervalMs: 5000
  #wait time for subsequent sync
    #waitTimeInMsWhenSyncEmpty: 5000