config:
  key: dev
aplicacion:
  name: miaplicacion
  texto: hola555546465465
  zuulconfig:
    host: localhost
    port: 8099
  kafka:
    topic-name: TEST
    topic-json-name: TESTJSON
    group-id: mygroup
    enable-consumers: false #activa o desactiva los consumidores de topic kafka

server:
  servlet:
    context-path: /microservicio # esto hace que el contexto el microservicio sea http://localhost:8080/microservicio/kafka/producer/9

eureka:
  client:
    registerWithEureka: true #para activar el registro en eureka -> true
    fetchRegistry: true #para activar el registro en eureka -> true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    initialStatus: UP
    #leaseExpirationDurationInSeconds: 5
    #leaseRenewalIntervalInSeconds: 5
    healthCheckUrlPath: /actuator/health
    statusPageUrlPath: /actuator/info  

spring:
   kafka:
     consumer:
        bootstrap-servers: 192.168.1.126:9092,192.168.1.126:9093,192.168.1.126:9094
        auto-offset-reset: earliest
     producer:
        bootstrap-servers: 192.168.1.126:9092,192.168.1.126:9093,192.168.1.126:9094