spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: repository/apps/config

eureka:
  client:
    registerWithEureka: false #para activar el registro en eureka -> true
    fetchRegistry: false #para activar el registro en eureka -> true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    initialStatus: UP
    #leaseExpirationDurationInSeconds: 5
    #leaseRenewalIntervalInSeconds: 5
    #healthCheckUrlPath: /actuator/health
    #statusPageUrlPath: /actuator/info  